spring.application.name=lld

# ===============================
# ORACLE DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=Fj5Vppy7rJu_THRD_Neo_3_13
spring.datasource.password=0n3-NETwork!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# ===============================
# JPA CONFIG
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# ===============================
# HIKARI POOL
# ===============================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

logging.level.org.springframework.security=DEBUG


server.port=9000
server.servlet.context-path=/api

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=porikasabapatisourab@gmail.com
spring.mail.password=eqph oszb nrnv zgzh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

